experiments:
- category: arxiv_medium
  domain: arxiv
  filename: arxiv_medium_w512_ov0_g0.yml
  global_tokens: 0
  id: 1
  length_category: medium
  overlap: 0
  overlap_ratio: 0%
  window_size: 512
- category: arxiv_medium
  domain: arxiv
  filename: arxiv_medium_w1024_ov0_g0.yml
  global_tokens: 0
  id: 2
  length_category: medium
  overlap: 0
  overlap_ratio: 0%
  window_size: 1024
- category: arxiv_medium
  domain: arxiv
  filename: arxiv_medium_w2048_ov0_g0.yml
  global_tokens: 0
  id: 3
  length_category: medium
  overlap: 0
  overlap_ratio: 0%
  window_size: 2048
- category: arxiv_medium
  domain: arxiv
  filename: arxiv_medium_w512_ov128_g16.yml
  global_tokens: 16
  id: 4
  length_category: medium
  overlap: 128
  overlap_ratio: 25%
  window_size: 512
- category: arxiv_medium
  domain: arxiv
  filename: arxiv_medium_w1024_ov256_g16.yml
  global_tokens: 16
  id: 5
  length_category: medium
  overlap: 256
  overlap_ratio: 25%
  window_size: 1024
- category: arxiv_medium
  domain: arxiv
  filename: arxiv_medium_w2048_ov512_g16.yml
  global_tokens: 16
  id: 6
  length_category: medium
  overlap: 512
  overlap_ratio: 25%
  window_size: 2048
- category: arxiv_long
  domain: arxiv
  filename: arxiv_long_w512_ov0_g0.yml
  global_tokens: 0
  id: 7
  length_category: long
  overlap: 0
  overlap_ratio: 0%
  window_size: 512
- category: arxiv_long
  domain: arxiv
  filename: arxiv_long_w1024_ov0_g0.yml
  global_tokens: 0
  id: 8
  length_category: long
  overlap: 0
  overlap_ratio: 0%
  window_size: 1024
- category: arxiv_long
  domain: arxiv
  filename: arxiv_long_w2048_ov0_g0.yml
  global_tokens: 0
  id: 9
  length_category: long
  overlap: 0
  overlap_ratio: 0%
  window_size: 2048
- category: arxiv_long
  domain: arxiv
  filename: arxiv_long_w512_ov128_g16.yml
  global_tokens: 16
  id: 10
  length_category: long
  overlap: 128
  overlap_ratio: 25%
  window_size: 512
- category: arxiv_long
  domain: arxiv
  filename: arxiv_long_w1024_ov256_g16.yml
  global_tokens: 16
  id: 11
  length_category: long
  overlap: 256
  overlap_ratio: 25%
  window_size: 1024
- category: arxiv_long
  domain: arxiv
  filename: arxiv_long_w2048_ov512_g16.yml
  global_tokens: 16
  id: 12
  length_category: long
  overlap: 512
  overlap_ratio: 25%
  window_size: 2048
- category: arxiv_extra_long
  domain: arxiv
  filename: arxiv_extra_long_w512_ov0_g0.yml
  global_tokens: 0
  id: 13
  length_category: extra_long
  overlap: 0
  overlap_ratio: 0%
  window_size: 512
- category: arxiv_extra_long
  domain: arxiv
  filename: arxiv_extra_long_w1024_ov0_g0.yml
  global_tokens: 0
  id: 14
  length_category: extra_long
  overlap: 0
  overlap_ratio: 0%
  window_size: 1024
- category: arxiv_extra_long
  domain: arxiv
  filename: arxiv_extra_long_w2048_ov0_g0.yml
  global_tokens: 0
  id: 15
  length_category: extra_long
  overlap: 0
  overlap_ratio: 0%
  window_size: 2048
- category: arxiv_extra_long
  domain: arxiv
  filename: arxiv_extra_long_w512_ov128_g16.yml
  global_tokens: 16
  id: 16
  length_category: extra_long
  overlap: 128
  overlap_ratio: 25%
  window_size: 512
- category: arxiv_extra_long
  domain: arxiv
  filename: arxiv_extra_long_w1024_ov256_g16.yml
  global_tokens: 16
  id: 17
  length_category: extra_long
  overlap: 256
  overlap_ratio: 25%
  window_size: 1024
- category: arxiv_extra_long
  domain: arxiv
  filename: arxiv_extra_long_w2048_ov512_g16.yml
  global_tokens: 16
  id: 18
  length_category: extra_long
  overlap: 512
  overlap_ratio: 25%
  window_size: 2048
- category: arxiv_extra_long
  domain: arxiv
  filename: arxiv_extra_long_w1024_ov256_g64.yml
  global_tokens: 64
  id: 19
  length_category: extra_long
  overlap: 256
  overlap_ratio: 25%
  window_size: 1024
- category: arxiv_extra_long
  domain: arxiv
  filename: arxiv_extra_long_w1024_ov512_g16.yml
  global_tokens: 16
  id: 20
  length_category: extra_long
  overlap: 512
  overlap_ratio: 50%
  window_size: 1024
- category: arxiv_extra_long
  domain: arxiv
  filename: arxiv_extra_long_w1024_ov512_g64.yml
  global_tokens: 64
  id: 21
  length_category: extra_long
  overlap: 512
  overlap_ratio: 50%
  window_size: 1024
- category: longform_medium
  domain: longform
  filename: longform_medium_w512_ov0_g0.yml
  global_tokens: 0
  id: 22
  length_category: medium
  overlap: 0
  overlap_ratio: 0%
  window_size: 512
- category: longform_medium
  domain: longform
  filename: longform_medium_w1024_ov0_g0.yml
  global_tokens: 0
  id: 23
  length_category: medium
  overlap: 0
  overlap_ratio: 0%
  window_size: 1024
- category: longform_medium
  domain: longform
  filename: longform_medium_w2048_ov0_g0.yml
  global_tokens: 0
  id: 24
  length_category: medium
  overlap: 0
  overlap_ratio: 0%
  window_size: 2048
- category: longform_medium
  domain: longform
  filename: longform_medium_w512_ov128_g16.yml
  global_tokens: 16
  id: 25
  length_category: medium
  overlap: 128
  overlap_ratio: 25%
  window_size: 512
- category: longform_medium
  domain: longform
  filename: longform_medium_w1024_ov256_g16.yml
  global_tokens: 16
  id: 26
  length_category: medium
  overlap: 256
  overlap_ratio: 25%
  window_size: 1024
- category: longform_medium
  domain: longform
  filename: longform_medium_w2048_ov512_g16.yml
  global_tokens: 16
  id: 27
  length_category: medium
  overlap: 512
  overlap_ratio: 25%
  window_size: 2048
- category: longform_long
  domain: longform
  filename: longform_long_w512_ov0_g0.yml
  global_tokens: 0
  id: 28
  length_category: long
  overlap: 0
  overlap_ratio: 0%
  window_size: 512
- category: longform_long
  domain: longform
  filename: longform_long_w1024_ov0_g0.yml
  global_tokens: 0
  id: 29
  length_category: long
  overlap: 0
  overlap_ratio: 0%
  window_size: 1024
- category: longform_long
  domain: longform
  filename: longform_long_w2048_ov0_g0.yml
  global_tokens: 0
  id: 30
  length_category: long
  overlap: 0
  overlap_ratio: 0%
  window_size: 2048
- category: longform_long
  domain: longform
  filename: longform_long_w512_ov128_g16.yml
  global_tokens: 16
  id: 31
  length_category: long
  overlap: 128
  overlap_ratio: 25%
  window_size: 512
- category: longform_long
  domain: longform
  filename: longform_long_w1024_ov256_g16.yml
  global_tokens: 16
  id: 32
  length_category: long
  overlap: 256
  overlap_ratio: 25%
  window_size: 1024
- category: longform_long
  domain: longform
  filename: longform_long_w2048_ov512_g16.yml
  global_tokens: 16
  id: 33
  length_category: long
  overlap: 512
  overlap_ratio: 25%
  window_size: 2048
- category: longform_extra_long
  domain: longform
  filename: longform_extra_long_w512_ov0_g0.yml
  global_tokens: 0
  id: 34
  length_category: extra_long
  overlap: 0
  overlap_ratio: 0%
  window_size: 512
- category: longform_extra_long
  domain: longform
  filename: longform_extra_long_w1024_ov0_g0.yml
  global_tokens: 0
  id: 35
  length_category: extra_long
  overlap: 0
  overlap_ratio: 0%
  window_size: 1024
- category: longform_extra_long
  domain: longform
  filename: longform_extra_long_w2048_ov0_g0.yml
  global_tokens: 0
  id: 36
  length_category: extra_long
  overlap: 0
  overlap_ratio: 0%
  window_size: 2048
- category: longform_extra_long
  domain: longform
  filename: longform_extra_long_w512_ov128_g16.yml
  global_tokens: 16
  id: 37
  length_category: extra_long
  overlap: 128
  overlap_ratio: 25%
  window_size: 512
- category: longform_extra_long
  domain: longform
  filename: longform_extra_long_w1024_ov256_g16.yml
  global_tokens: 16
  id: 38
  length_category: extra_long
  overlap: 256
  overlap_ratio: 25%
  window_size: 1024
- category: longform_extra_long
  domain: longform
  filename: longform_extra_long_w2048_ov512_g16.yml
  global_tokens: 16
  id: 39
  length_category: extra_long
  overlap: 512
  overlap_ratio: 25%
  window_size: 2048
- category: longform_extra_long
  domain: longform
  filename: longform_extra_long_w1024_ov256_g64.yml
  global_tokens: 64
  id: 40
  length_category: extra_long
  overlap: 256
  overlap_ratio: 25%
  window_size: 1024
- category: longform_extra_long
  domain: longform
  filename: longform_extra_long_w1024_ov512_g16.yml
  global_tokens: 16
  id: 41
  length_category: extra_long
  overlap: 512
  overlap_ratio: 50%
  window_size: 1024
- category: longform_extra_long
  domain: longform
  filename: longform_extra_long_w1024_ov512_g64.yml
  global_tokens: 64
  id: 42
  length_category: extra_long
  overlap: 512
  overlap_ratio: 50%
  window_size: 1024
